dtrace-parser/src/lib.rs
usdt-macro/Cargo.toml
usdt-macro/src/lib.rs

- Adds a concrete error type used to represent errors while parsing the
D provider file using Pest.
- Adds a slightly better error message when including unsupported data
types, and handles/unpacks that in the procedural macro. Compile-time
messages now show a span around the offending D source file, and provide
a hint to check the types.

Improves handling of parse errors

---

Cargo.toml
tests/empty/provider.d
tests/zero-arg-probe/Cargo.toml
tests/zero-arg-probe/build.rs
tests/zero-arg-probe/src/main.rs
tests/zero-arg-probe/test.d
usdt-impl/src/empty.rs
usdt-impl/src/linker.rs
usdt-impl/src/no-linker.rs

This allows a probe with zero arguments to be invoked without a closure (optionally).

simplify use of probes with zero arguments

---

.github/workflows/rust.yml
usdt-impl/src/lib.rs
usdt-impl/src/linker.rs

In the linker version of this crate, we rely on `dtrace(1)` to generate
a header file, and then parse that to construct the probe macros. The
previous implementation used temporary files to cache the provider and
the generated header, passing those to `dtrace(1)` in the `-s` and `-o`
flags. These files are in a temporary directory, but they have the same
name, so if the temp-dir is the same, that file will be overwritten if
there are concurrent builds. One situation in which that is actually
pretty likely to happen is testing. One test will may see a corrupt
provider or header output file, and thus fail in odd and confusing ways.
This commit addresses this by using stdin/stdout to communicate the
provider and header files with the `dtrace(1)` subprocess.
It also makes testing on CI …

Fixes racy use of tempfiles when calling out to DTrace

---

.github/workflows/rust.yml
probe-test-macro/Cargo.toml
usdt-impl/Cargo.toml
usdt-impl/src/common.rs
usdt-impl/src/empty.rs
usdt-impl/src/lib.rs
usdt-impl/src/linker.rs
usdt-impl/src/no-linker.rs
usdt-impl/src/record.rs
usdt-macro/Cargo.toml
usdt/Cargo.toml

platform dynamic linker
- Adds the `"no-linker"` feature flag to the `usdt` and `usdt-impl`
crates, forwarding the former to the latter
- Better conditional compilation of the `usdt_impl::internal` module,
based on the platform and new set of feature flags
- Combines some of the shared code used to generate the USDT macros
themselves into a `usdt-impl/src/common.rs` mod. The actual
implementation of the macro in the macos/linker case has been updated.
Previously, we were directly calling the (linker-defined) probe function
by creating a Rust fn with link-name of that mangled probe function.
This mapped directly onto the "usual" C implementation. That has been
updated to marshal the arguments just as we do on no-linker platforms,
and use the x86 call instruction directly. This all works, …

Adds no-linker feature for building on macos without relying on the

---

.github/workflows/rust.yml
Cargo.toml
dtrace-parser/src/lib.rs
tests/compile-errors/Cargo.toml
tests/compile-errors/providers/type-mismatch.d
tests/compile-errors/providers/unsupported-type.d
tests/compile-errors/src/lib.rs
tests/compile-errors/src/no-closure.rs
tests/compile-errors/src/no-closure.stderr
tests/compile-errors/src/no-provider-file.rs
tests/compile-errors/src/no-provider-file.stderr
tests/compile-errors/src/type-mismatch.rs
tests/compile-errors/src/type-mismatch.stderr
tests/compile-errors/src/unsupported-type.rs
tests/compile-errors/src/unsupported-type.stderr
usdt-impl/src/lib.rs
usdt-macro/src/lib.rs
usdt/Cargo.toml

- Adds a suite of tests which verify the compiler error messages when
the `usdt` crate is misused in various likely ways. This includes a
provider definition with an unsupported type, a type mismatch in the
probe macro invocation, calling the probe macro without a closure, and
specifying a non-existent provider file to the proc macro or build.rs.
- Adds back the `asm` feature as a default and updates the CI config
accordingly.
- More appropriate conditional compilation of the actual internal
implementation file under various combinations of platform a feature
flags.

Adds tests to verify useful error messages when compiling fails

---

Cargo.toml
dof/Cargo.toml
dof/src/dof.rs
dof/src/lib.rs
dusty/Cargo.toml
dusty/src/main.rs
usdt-impl/Cargo.toml
usdt-impl/src/lib.rs
usdt-impl/src/no-linker.rs
usdt-impl/src/record.rs
usdt/Cargo.toml
usdt/src/lib.rs

- Removes extraneous structopt dep from `dof` crate
- Adds a "des" feature to many of the packages. This is used to gate
inclusion of the tools for deserializing the probe records or DOF itself
from an object file. The effect on the dependency tree is to make the
large `goblin` dependency optional.
- Adds a small, separate binary crate `dusty`, which has the binary for
actually reading the DOF or ASM records from an object file. This is
really just the former `usdt/src/main.rs`, with appropriate changes to
the feature flags and depdendency tree.
- Note that the `"dof/des"` flag is not a default feature. It is opted
into via the `"usdt/des"` feature, which is _not_ implied by the "asm"
and "no-linker" features of the same crate. This allows the
deserialization tooling to be opted _out_ of, …

Prunes the dependency tree

---

Cargo.toml
tests/does-it-work/Cargo.toml
tests/does-it-work/build.rs
tests/does-it-work/src/main.rs
tests/does-it-work/test.d
usdt-impl/src/record.rs
usdt/src/lib.rs

- Adds the `tests/does-it-work` crate to the workspace. This builds a
single probe, and then runs DTrace to verify that that probe is listed
with the correct properties. This relies on passwordless sudo, available
on GitHub's CI, or that the test itself is actually run with `sudo
cargo`.
- Removes stray println in the extraction of probe information from an
object file, left over from development.
- Bolds the comment in the README that the generated macros should be
included in the crate root.

Adds integration test verifying that a probe is visible via `dtrace(1)`

---

.gitignore
README.md
probe-test-macro/src/main.rs
usdt-macro/src/lib.rs

@pfmooney observed that rust-analyzer runs builds from a different cwd than if one runs `cargo build` by hand. Consequently, the `dtrace_provider!` macro looks for the provider file in the wrong place. This PR uses `CARGO_MANIFEST_DIR` as the base directory in which we look for the specified provider file.

update the path where we look for the provider.d file to appease rust-analyzer

---

tests/compile-errors/src/no-closure.stderr
tests/compile-errors/src/type-mismatch.stderr
tests/compile-errors/src/unsupported-type.stderr
usdt-impl/src/no-linker.rs

Before:
If `/dev/dtrace/helper` was missing, due to (for example) a missing package, probe registration would return a "bad fd" error, after attempting to issue an ioctl to a defunct file descriptor.
After:
Well, if `/dev/dtrace/helper` is gone, things are still gonna fail, but the error will be slightly more comprehensible - it should fail due to "missing file/device", which is more accurate.

Avoid issuing ioctl on bad fd

---

probe-test-build/src/main.rs
probe-test-build/test.d
probe-test-macro/src/main.rs
probe-test-macro/test.d
usdt-impl/src/common.rs

This expansion of one of the macros may best exemplify this change (hand re-formatted):
```rust
macro_rules ! test_stop {
($tree:tt) => {
compile_error!("USDT probe macros should be invoked with a closure returning the arguments");
};
($args_lambda:expr) => {
{
fn _type_check<S: AsRef<str>>(_: S, _: u8, _ :S) { }
let _ = || {
let args = $args_lambda();
_type_check(args.0, args.1, args.2);
};
}
unsafe {
if $crate::__usdt_private_test::test_stop_enabled() != 0 {
let args = $args_lambda();
let arg_0 = [(args.0.as_ref() as &str).as_bytes(), &[0_u8]].concat();
let arg_1 = (args.1 as i64);
let arg_2 = [(args.2.as_ref() as &str).as_bytes(), &[0_u8]].concat();
asm!(
".reference {typedefs}",
"call {probe_fn}",
".reference {stability}",
typedefs = sym $crate::__usdt_private_test::typedefs,
probe_fn …
```

fix issues relating to data not living long enough

---

dtrace-parser/src/lib.rs
tests/compile-errors/Cargo.toml
tests/compile-errors/src/different-serializable-type.rs
tests/compile-errors/src/different-serializable-type.stderr
tests/compile-errors/src/lib.rs
tests/compile-errors/src/zero-arg-probe-type-check.rs
tests/compile-errors/src/zero-arg-probe-type-check.stderr
tests/test-json/src/main.rs
usdt-attr-macro/src/lib.rs
usdt-impl/src/common.rs
usdt-impl/src/no-linker.rs

The internal type-checking mechanisms were broken for probes with no
arguments. One could write an argument closure returning _any_
arguments, and this would "pass" our internal type-checking, as we only
unpacked the _expected_ arguments from the closure. As there were no
expected arguments, there was no type-checking.
This commit modifies type-checking to verify that if the probe expects
zero arguments, we can assign the result of calling the argument closure
to a variable of type `()`. It also modifies the type checking of
serializable types. Before we used a generic parameter with a trait
bound `T: ::serde::Serialize`. This is actually not enough, since it
would successfully type-check an argument closure that returns a
_different_ type that is serializable than the one in the probe …

Fixes type checking for probes with zero arguments

---

usdt-impl/src/lib.rs
usdt-impl/src/no-linker.rs
usdt-impl/src/record.rs
usdt/src/lib.rs

This commit adds support for guaranteed at-most-once registration of
probes, within a single process lifetime. The linker section into which
the probes are written is now writable. When reading a probe record, the
code checks that the probe's version is supported, and, if so,
atomically exchanges it for a sentinel value (255), returning the
original. Since any probe version greater than the crate's version is
skipped, probes that are handled will be skipped in any other invocation
of the `register_probes` function, as those probes' version is now the
sentinel. Unhandled probes will not be modified, but will still be
skipped, letting later versions of the library handle them.

Implements one-time registration of probes in a process

---

usdt-attr-macro/Cargo.toml
usdt-impl/Cargo.toml
usdt-macro/Cargo.toml
usdt/Cargo.toml

- `usdt-impl`: 0.1.12 -> 0.1.13
- `usdt-macro`: 0.1.13 -> 0.1.14
- `usdt-attr-macro`: 0.1.3 -> 0.1.4
- `usdt`: 0.1.17 -> 0.1.18
Also replaces exact version dependencies on other crates in the
workspace. This was moved earlier, but should not have been.

Bumps versions for release

---

dtrace-parser/Cargo.toml
usdt-attr-macro/Cargo.toml
usdt-impl/Cargo.toml
usdt-macro/Cargo.toml
usdt/Cargo.toml

- `dtrace-parser` 0.1.11 -> 0.1.12
- `usdt-impl` 0.1.13 -> 0.1.14
- `usdt-macro` 0.1.14 -> 0.1.15
- `usdt-attr-macro` 0.1.4 -> 0.1.5
- `usdt` 0.1.18 -> 0.1.19

Bump versions for release

---

usdt-impl/src/empty.rs

Fixes incorrect use of cloned argument closure in empty implementation

---

usdt-attr-macro/Cargo.toml
usdt-macro/Cargo.toml
usdt/Cargo.toml

The dependency resolver v2 does not merge features in the same way as
prior versions. V2 is also the default as of Rust edition 2021. This
could lead to incorrectly building multiple versions of the usdt crate,
including one erroneously selecting the empty implementation.
This adds feature flags for the `usdt-macro` and `usdt-attr-macro`
crates that ensure we're building with the correct set of flags
regardless of which resolver is used.

Supports crates using the new resolver v2

---

Cargo.toml
tests/rename-builder/Cargo.toml
tests/rename-builder/build.rs
tests/rename-builder/src/main.rs
tests/rename-builder/test.d
tests/rename/Cargo.toml
tests/rename/src/main.rs
usdt-attr-macro/src/lib.rs
usdt-impl/src/common.rs
usdt-impl/src/empty.rs
usdt-impl/src/lib.rs
usdt-impl/src/linker.rs
usdt-impl/src/no-linker.rs
usdt/src/lib.rs

After the change to module-scoped macros, we kept the ability to rename
the probe module from the earlier implementation. This meant the
procedural macros might rename the module, which is a bit confusing.
This switches to support renaming the _provider_, but not the module.
The module can be named to whatever the user wishes, and the probes are
always available in that scope. If the provider name is not chosen in
the attribute macro, it defaults to the module name, but this can be
overridden.

Allows renaming the provider, rather than the probe module

---

README.md
dusty/Cargo.toml
usdt-attr-macro/Cargo.toml
usdt-impl/Cargo.toml
usdt-macro/Cargo.toml
usdt/Cargo.toml
usdt/src/lib.rs

- `usdt-impl` 0.1.14 -> 0.2.0
- `usdt-macro` 0.1.15 -> 0.2.0
- `usdt-attr-macro` 0.1.5 -> 0.2.0
- `usdt` 0.1.19 -> 0.2.0

Documentation cleanup and bump versions for release

---

Cargo.toml
tests/modules/Cargo.toml
tests/modules/src/inner.rs
tests/modules/src/main.rs
usdt-impl/src/common.rs
usdt-impl/src/empty.rs
usdt-impl/src/linker.rs
usdt-impl/src/no-linker.rs

On macOS, we define extern functions with valid Rust identifiers for a
few key bits of information about the providers and probes. These
symbols are generated by the macOS linker, but we collect their names
from the output of `dtrace -h` during macro generation.
Previously these symbols were defined in a separate scope that the
actual probe declarative macro bodies. For example, the stability symbol
was defined in the provider module, so one "level" of scope above the
probe macro bodies. This means we need to be able to refer to that
symbol by path, which is difficult, since the probe modules can
generally be anywhere in the crate at this point.
This moves those extern symbols directly into the scope of the probe
macro body. They can just be referred to without any other path
components …

Moves extern symbol definitions into the macro bodies on macOS

---

dusty/Cargo.toml
tests/compile-errors/src/unsupported-type.stderr
usdt-attr-macro/Cargo.toml
usdt-impl/Cargo.toml
usdt-impl/src/common.rs
usdt-impl/src/lib.rs
usdt-impl/src/record.rs
usdt-macro/Cargo.toml
usdt/Cargo.toml
usdt/src/lib.rs

- Any `__` in provider or probe names is now translated into `-`, inline
with how DTrace probes are renamed in C, and to support the
convention.
- Small doc fixes

Adds support for translating double-underscores to dashes

---

README.md
dtrace-parser/src/dtrace.pest
dtrace-parser/src/lib.rs
probe-test-attr/src/main.rs
usdt-attr-macro/src/lib.rs
usdt-impl/src/common.rs
usdt-impl/src/lib.rs
usdt-impl/src/record.rs
usdt-macro/src/lib.rs
usdt/src/lib.rs

- Reworks some of the internal dtrace-parser code to make integers more
compact and easily represent pointers.
- Adds support for pointers the implementation crates
- Adds pointers to list of supported types
- Adds a probe in the `probe-test-attr` crate that uses a pointer.

Add support for const pointers to integer types

---

common-build.rs
dtrace-parser/src/lib.rs
dusty/Cargo.toml
dusty/src/main.rs
probe-test-build/build.rs
tests/argument-types/src/main.rs
tests/does-it-work/build.rs
tests/empty/build.rs
tests/fake-lib/build.rs
tests/rename-builder/build.rs
tests/zero-arg-probe/build.rs
usdt-attr-macro/Cargo.toml
usdt-attr-macro/src/lib.rs
usdt-impl/Cargo.toml
usdt-impl/build.rs
usdt-impl/src/common.rs
usdt-impl/src/empty.rs
usdt-impl/src/lib.rs
usdt-impl/src/no-linker.rs
usdt-impl/src/record.rs
usdt-macro/Cargo.toml
usdt-macro/src/lib.rs
usdt/Cargo.toml
usdt/src/lib.rs

This retools `asm` and `asm_sym` feature inside the usdt implementation to make fallback more smooth when built with a compiler which does not support the necessary features.  Consumers wanting the old behavior, where the crate will fail to build if they do not have a supported compiler and necessary enabled features, is preserved with the `strict-asm` feature.  Without `strict-asm` enabled, the usdt-impl `build.rs` will quietly fall back to the no-op probe implementation if compiler functionality is not met.

More stable asm

---

dtrace-parser/Cargo.toml
usdt-attr-macro/Cargo.toml
usdt-impl/Cargo.toml
usdt-macro/Cargo.toml
usdt/Cargo.toml

A previous commit removed the version specification for the path dependencies in the repository. This all works fine, until the crates are published. Crates on crates.io may not have path dependencies, but there is no version to use.
The accepted solution appears to be to specify _both_ path and version dependencies. The former is used when building from source, the latter when publishing.

Add both path and version dependencies

---

Cargo.lock
dusty/Cargo.toml
dusty/src/main.rs
usdt-impl/src/no-linker.rs
usdt-impl/src/record.rs

- The `dusty` binary now `mmap`s the target file, rather than reading the whole thing in. This trades a bit of speed in the form of page faults, for laziness, and only reads the required portions of the file.
- Reworks how we read and potentially update the probe record version stored in the target file. First, adds an argument to the `process_section` function controlling whether we want to bother updating the version. `dusty` does not set this, whereas the code that registers the probes does. Second, makes the bytes in which the probe records are stored mutable everywhere, which properly communicates the intent that these may be updated. Lastly, we avoid further inline assembly and some portability issues by using an atomic rather than a `lock xchg` instruction. That currently works by …

Reworks probe record version manipulation

---

.github/workflows/rust.yml
Cargo.lock
dof/Cargo.toml
dof/src/dof.rs
dof/src/fmt.rs
dusty/Cargo.toml
dusty/src/main.rs

Having just recently learned out useful dtrace is, I'm on a bit of a mission to make what we can do with it more visible. The first part in that story is making it easier to programmatically munge the output of dusty, thus a new JSON mode.
I updated `dof` to include serde serialization of the `Section` struct and its children. I did make a breaking change to `fmt_dof` to have it take in an enum struct called `FormatMode` instead of the flags it was previously taking. The flags were somewhat misrepresentative because `include_sections` was only relevant when in raw mode. Overall I just felt this a better mechanism of invocation, especially when considering adding a new flag.

Add JSON support to dusty

---

.github/workflows/rust.yml
Cargo.lock
tests/does-it-work/src/main.rs
tests/test-json/Cargo.toml
tests/test-json/src/main.rs
usdt-tests-common/src/lib.rs

The tests for JSON output work by starting DTrace as a subprocess; firing some probes in the Rust test code; and then grabbing the DTrace output and verifying its properties. There was a race here: although we waited to fire the probes until requested, we never actually waited for DTrace to correctly start and indicate readiness. Test hangs ensue, at least on macOS where `sudo` actually requires a password in most cases.
This adds synchronization in the other direction, waiting for DTrace to print a sentinel in its BEGIN clause, so that the tests don't start until it has successfully spawned.
Fixes #155

Fix race in JSON tests

---

.github/workflows/rust.yml
Cargo.lock
dof/Cargo.toml
dof/src/des.rs
dof/src/dof_bindings.rs
dof/src/fmt.rs
dtrace-parser/Cargo.toml
usdt-attr-macro/Cargo.toml

- Update to `rstest v0.18.2`, which requires another toolchain bump for a transitive dep. We're now at 1.66 for the older nightly tests.
- Update `zerocopy v0.7.32`, which changed public traits

Some dependency updates that require manual work

---

.github/workflows/rust.yml
usdt-impl/src/record.rs

- Don't use any dynamic loading constructions on Windows
- Add CI target for Windows

`dladdr(3c)` doesn't exist on Windows

---

Cargo.lock
dof/src/fmt.rs
usdt/Cargo.toml
usdt/src/lib.rs

The original `memmap` crate has been unmaintained for a while now. This switches to the API-compatible `memmap2` crate. Closes #227.

Move to memmap2

---

usdt-impl/src/common.rs

Fixes #240, by casting pointers to `usize` instead of `i64`, which should always be lossless.

Cast pointers to usize to avoid new Clippy lints

---

.github/workflows/rust.yml
rust-toolchain.toml
tests/argument-types/src/main.rs
usdt-impl/build.rs
usdt-impl/src/lib.rs

Also improved CI to ensure that we test on the MSRV and on the latest stable release.
With this we run:
* most tests on MSRV + stable
* trybuild tests on the pinned version
ensuring good coverage across our supported matrix.
Supersedes (and includes) https://github.com/oxidecomputer/usdt/pull/268.

[meta] update pinned toolchain to Rust 1.80

---

.github/workflows/rust.yml
tests/compile-errors/src/different-serializable-type.stderr
usdt-attr-macro/src/lib.rs
usdt-impl/src/common.rs
usdt-impl/src/empty.rs
usdt-impl/src/linker.rs
usdt-impl/src/no-linker.rs
usdt/src/lib.rs

- Rework construction of the internal type-checking function to remove the clone requirement. Construct and call the type-check-function right at the site we already expand the probe argument closure, rather than outside. This means we don't need to expand things twice, and don't need to clone the closure, and so don't need the argument types to be cloneable either.
- Fixup tests for new method, add some comments.
- Update trybuild tests
- Closes #136

Remove `Clone` requirement for argument types

---

.github/workflows/rust.yml
tests/does-it-work/src/main.rs
usdt-impl/src/stapsdt/args.rs

A mistake I managed to slip in as part of #340: an errant `cfg` (leftovers from a previous version of the code) made the function remove all of its important parts if the machine was not x86_64.
This wasn't caught by CI because none of the CI builds actually run on Arm currently. I added running on macos-latest which are aarch64 machines.

fix: remove invalid cfg requirement for x86_64 in integer_to_asm_op

---

tests/does-it-work/src/main.rs
usdt-impl/src/linker.rs
usdt-impl/src/no-linker.rs
usdt-impl/src/stapsdt.rs

Four days of debugging and discussions came to this: I very much should have noticed that my readelf output had zeroes as the "Base" address which should never be zero ~~unless the semaphore address also is zero~~. This was my linker GC'ing the `_.stapsdt.base` section out of the final executable because it's not being referred to from any allocated section. Programs that unconditionally use this base section ended up doing very bad things to programs being traced, so running `perf stat` to record USDT probes firing would crash the program being traced. Oops! And it turns out this was not just [mold](https://github.com/rui314/mold/issues/1510) linker but also lld and gold; only ld is excempt!
The SystemTap folks are now considering adding the "R" GNU_SHF_RETAIN flag to `sys/sdt.h` so it …

fix: add "R" GNU_SHF_RETAIN to stapsdt.rs .stapsdt.base section
